// SPDX-License-Identifier: GPL-3.0-or-later
pub mod agenda;
pub mod audio;
pub mod clock;
pub mod cpu_temp;
pub mod dummy;
pub mod network;
pub mod network_m;
pub mod network_s;
pub mod network_sq;
pub mod network_sx;
pub mod registry;
pub mod shortcuts;
pub mod system_info;
pub mod temp_gauge;
pub mod weather;
pub mod youtube;
