[package]
name = "xeneon-app"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.9.2", package = "libadwaita", features = ["v1_5"] }
chrono = "0.4.45"
chrono-tz = "0.10.4"
gtk = { version = "0.11.4", package = "gtk4", features = ["v4_12"] }
relm4 = { version = "0.11.0", default-features = false, features = ["libadwaita", "gnome_47", "macros", "css"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.26.1", features = ["v4", "serde"] }
xeneon-core = { version = "0.1.0", path = "../xeneon-core" }
